# Generated by Django 5.0 on 2025-04-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='webVit',
            field=models.FileField(null=True, upload_to='Subtitle'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='audio',
            field=models.FileField(null=True, upload_to='Audio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subitle',
            field=models.FileField(null=True, upload_to='Subtitle'),
        ),
    ]
