# Generated by Django 5.0 on 2025-04-18 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_profile_webvit_alter_profile_audio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subitle',
            new_name='subtitle',
        ),
    ]
