# Generated by Django 5.0 on 2025-04-21 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_subitle_profile_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='webVit',
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(null=True, upload_to='Audio')),
                ('subtitle', models.FileField(null=True, upload_to='Subtitle')),
                ('webVit', models.FileField(null=True, upload_to='Subtitle')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.profile')),
            ],
        ),
    ]
