# Generated by Django 5.0 on 2025-04-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_profile_audio_remove_profile_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='actions',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='source_lang',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='target_lang',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
