# Generated by Django 5.0 on 2025-04-22 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_subtitle_actions_subtitle_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 22, 0, 37, 23, 137644, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtitle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
